Feature send registration mail
mongulu-cm/mtchoun-mouh pull request #94
Opened 2023-01-22 11:16 UTC by tsafacjo

2023-01-22 11:20 UTC, tsafacjo commented
I uploaded the mail template and use it to format registration mail.
Attached an example of mail screenshot

![image](https://user-images.githubusercontent.com/26392278/213913107-51d1b459-88fb-4f89-84c5-db545f3f0df1.png)

2023-01-22 16:22 UTC, billmetangmo requested changes
Very good template, it looks a way better than the weird email we had previously :) . I have left some reviews.

- [ ] Concerning the logo url on the template, I see that it is referenced through this URL https://zgpkul.stripocdn.email/content/guids/CABINET_150a1059e2ca27f83667e01c2e55d6e54f0f80bf71502abb42ec050d3d4ba80d/images/logo_mongulu.jpeg . Does it mean that you save the logo on stripo directly or stripo read it from S3 ? If stripo is not reading from S3, this mean we can delete public-images-mongulu bucket right ?

- [ ] Concerning the template itself, I have some remarks there: https://www.tldraw.com/r/27238cee-f4a3-4053-2a11-97ad84261b35 ( tldraw is an opensource drawer that i like because so esay to and simple to draw - c'est en mod écriture là donc t pourras supprimer ce que t'auras pris en compte ) 

- [ ] Concerning the template tool stripo.email, I see that it's not possible with free pricing to **add comments directly on the template** because it's limited to one user. **Do you check other tools that i allow to do email template and balance to choose stripo**. I know:

- https://www.figma.com/pricing/ who has unlimited users on free design ( figma comments included)
- https://www.canva.com/fr_fr/tarification/ ( canvas comments included)
- https://penpot.app/ ( which is opensource but dont check if unlimited users).

**PS: We will use the current template for this task, it's just to share with uou alternatives if     you didi not know or know why you choosed it over them. If you think, it  would have been better to use one of them. We will just create an issue for update but later as it's not really urgent.**

2023-01-22 17:52 UTC, tsafacjo commented on api/notify.py
> +    obj = s3.Object('templates-emails','mtchoun-mouh registration.html')
Yes, we could,.
 But I didn't code this template from scrash, I used an online tool https://my.stripo.email/cabinet/#/login?locale=fr.
I will update the code sun to take this remark into consideration.

2023-01-22 17:53 UTC, tsafacjo commented on api/notify.py
> +    )
OK,  I will adapt it soon.

2023-01-24 22:36 UTC, tsafacjo commented on api/notify.py
> +    obj = s3.Object('templates-emails','mtchoun-mouh registration.html')
For the template , No, we can not add it on the code, the file is to big about 258 lines.
We can just activate versionnning on the file in aws..

2023-01-25 18:41 UTC, billmetangmo commented on api/notify.py
> +    obj = s3.Object('templates-emails','mtchoun-mouh registration.html')
Normally it should be fine. If it's just 200 lines. What error github gives to you?

2023-01-26 11:15 UTC, billmetangmo commented
## Plan Result

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4014626566)


<pre><code>Plan: 2 to add, 3 to change, 0 to destroy.</code></pre>

* Create
  * local_file.demo_page
  * local_file.index_page
* Update
  * aws_lambda_function.lambda
  * aws_lambda_function.scan
  * aws_s3_bucket.website


<details><summary>Change Result (Click me)</summary>

```hcl

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:09:35.000+0000" -> (known after apply)
      ~ source_code_hash               = "Iv4V9iJooMU9YKBrrxk6KH7Mlb2Zg8hRahB9PKuyuiI=" -> "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-20T20:00:25.323+0000" -> (known after apply)
      ~ source_code_hash               = "C7ShCQBdjAY/jz+KquFnPS0i9PPTS2fSQ2zW2PQS9ks=" -> "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var URL = "https://c3msk8vrld.execute-api.eu-central-1.amazonaws.com/feature-send-registration-mail-dev/register";
            
                    var name = $("#name-input").val();
                    var data = {
                      name: name,
                    };
            
                    $.ajax({
                      type: "POST",
                      url: URL,
                      dataType: "json",
                      crossDomain: "true",
                      contentType: "application/json; charset=utf-8",
                      data: JSON.stringify(data),
            
                      success: function (response) {
                        // clear form and show a success message
                        $("#errorMessage>p").html(
                          "Nous avons  trouvé l <a href="+response["message"]+">image</a> d'où provient votre choix &#128578;"
            
                        );
                        $("#errorMessage").css("background", "#0f7555");
                        console.log("ok")
                        $("#errorMessage").modal("show");
                        document.getElementById("contact-form").reset();
                        //location.reload();
                      },
                      error: function () {
                        // show an error message
                        $("#errorMessage>p").html(
                          "Le nom rentré n'existe pas. \n Veuillez vérifier l'orthographe. "
                        );
                        $("#errorMessage").modal("show");
                        //location.reload();
                      },
                    });
                  }
                </script>
              </head>
              <body class="text-center">
                <!--https://aws.amazon.com/fr/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/-->
                <form id="contact-form" method="post" class="form-signin">
                  <div class="mb-2">
                    <img alt="Logo cameroun" width="150" src="Armoiries_cameroun.svg" />
                  </div>
                  <h1 class="h5 font-weight-normal highlight">Si vous êtes là c'est que vous voulez une démonstration. Pas de soucis &#128578; </h1>
                  <h2 class="h6 font-weight-normal highlight">Nous vous proposons donc de choisir un nom au hasard dans le [...]

2023-01-26 11:15 UTC, billmetangmo commented
## :white_check_mark: Apply Succeeded

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4014626566)



<pre><code>Apply complete! Resources: 2 added, 3 changed, 0 destroyed.</code></pre>

<details><summary>Details (Click me)</summary>

```hcl
[command]/home/runner/work/_temp/745d7868-f7b0-47b2-ac6b-cb02e14cd848/terraform-bin apply -auto-approve -no-color
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 0s [id=e3ed38f064ae470d1d6ad12b27efc9e0dba235a5]
aws_dynamodb_table.Link_table: Refreshing state... [id=feature-send-registration-mail-Link_table]
aws_dynamodb_table.Register: Refreshing state... [id=feature-send-registration-mail-Register]
data.aws_caller_identity.current: Reading...
aws_cloudwatch_event_rule.scheduler: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan]
data.aws_iam_policy_document.override: Reading...
aws_dynamodb_table.Users: Refreshing state... [id=feature-send-registration-mail-Users]
aws_api_gateway_rest_api.api: Refreshing state... [id=c3msk8vrld]
data.aws_iam_role.role: Reading...
data.aws_iam_policy_document.override: Read complete after 0s [id=2656879482]
aws_s3_bucket.images: Refreshing state... [id=feature-send-registration-mail-djansang]
aws_s3_bucket.website: Refreshing state... [id=feature-send-registration-mail-mtchoun-mouh.mongulu.cm]
data.aws_caller_identity.current: Read complete after 0s [id=053932140667]
data.aws_iam_role.role: Read complete after 0s [id=website-deployer]
aws_lambda_function.scan: Refreshing state... [id=feature-send-registration-mail-scan_user_consulcam]
aws_lambda_function.lambda: Refreshing state... [id=feature-send-registration-mail-user_registration_consulcam]
aws_api_gateway_resource.resource: Refreshing state... [id=nr7et2]
module.cors.aws_api_gateway_method._: Refreshing state... [id=agm-c3msk8vrld-nr7et2-OPTIONS]
aws_api_gateway_method.method: Refreshing state... [id=agm-c3msk8vrld-nr7et2-POST]
aws_lambda_permission.allow_cloudwatch_to_call_check_foo: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_cloudwatch_event_target.target: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan-lambda]
aws_api_gateway_method_response.method_response_200: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-POST-200]
aws_lambda_permission.apigw_lambda: Refreshing state... [id=AllowExecutionFromAPIGateway]
aws_api_gateway_integration.integration: Refreshing state... [id=agi-c3msk8vrld-nr7et2-POST]
module.cors.aws_api_gateway_method_response._: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-OPTIONS-200]
module.cors.aws_api_gateway_integration._: Refreshing state... [id=agi-c3msk8vrld-nr7et2-OPTIONS]
module.cors.aws_api_gateway_integration_response._: Refreshing state... [id=agir-c3msk8vrld-nr7et2-OPTIONS-200]
aws_api_gateway_deployment.test: Refreshing state... [id=pnx8wn]
local_file.demo_page: Refreshing state... [id=e3a19d09a1ff44f2e90820909bcc91c45dd6eef0]
local_file.index_page: Refreshing state... [id=d25db991d30eb07e3ad9ab147c19d8c8111115af]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:09:35.000+0000" -> (known after apply)
      ~ source_code_hash               = "Iv4V9iJooMU9YKBrrxk6KH7Mlb2Zg8hRahB9PKuyuiI=" -> "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-20T20:00:25.323+0000" -> (known after apply)
      ~ source_code_hash               = "C7ShCQBdjAY/jz+KquFnPS0i9PPTS2fSQ2zW2PQS9ks=" -> "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Nam [...]

2023-01-26 11:25 UTC, billmetangmo commented
## Plan Result

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4014698859)


<pre><code>Plan: 2 to add, 3 to change, 0 to destroy.</code></pre>

* Create
  * local_file.demo_page
  * local_file.index_page
* Update
  * aws_lambda_function.lambda
  * aws_lambda_function.scan
  * aws_s3_bucket.website


<details><summary>Change Result (Click me)</summary>

```hcl

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:15:45.000+0000" -> (known after apply)
      ~ source_code_hash               = "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY=" -> "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-26T11:15:42.000+0000" -> (known after apply)
      ~ source_code_hash               = "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY=" -> "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var URL = "https://c3msk8vrld.execute-api.eu-central-1.amazonaws.com/feature-send-registration-mail-dev/register";
            
                    var name = $("#name-input").val();
                    var data = {
                      name: name,
                    };
            
                    $.ajax({
                      type: "POST",
                      url: URL,
                      dataType: "json",
                      crossDomain: "true",
                      contentType: "application/json; charset=utf-8",
                      data: JSON.stringify(data),
            
                      success: function (response) {
                        // clear form and show a success message
                        $("#errorMessage>p").html(
                          "Nous avons  trouvé l <a href="+response["message"]+">image</a> d'où provient votre choix &#128578;"
            
                        );
                        $("#errorMessage").css("background", "#0f7555");
                        console.log("ok")
                        $("#errorMessage").modal("show");
                        document.getElementById("contact-form").reset();
                        //location.reload();
                      },
                      error: function () {
                        // show an error message
                        $("#errorMessage>p").html(
                          "Le nom rentré n'existe pas. \n Veuillez vérifier l'orthographe. "
                        );
                        $("#errorMessage").modal("show");
                        //location.reload();
                      },
                    });
                  }
                </script>
              </head>
              <body class="text-center">
                <!--https://aws.amazon.com/fr/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/-->
                <form id="contact-form" method="post" class="form-signin">
                  <div class="mb-2">
                    <img alt="Logo cameroun" width="150" src="Armoiries_cameroun.svg" />
                  </div>
                  <h1 class="h5 font-weight-normal highlight">Si vous êtes là c'est que vous voulez une démonstration. Pas de soucis &#128578; </h1>
                  <h2 class="h6 font-weight-normal highlight">Nous vous proposons donc de choisir un nom au hasard dans le [...]

2023-01-26 11:26 UTC, billmetangmo commented
## :white_check_mark: Apply Succeeded

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4014698859)



<pre><code>Apply complete! Resources: 2 added, 3 changed, 0 destroyed.</code></pre>

<details><summary>Details (Click me)</summary>

```hcl
[command]/home/runner/work/_temp/920c9812-28f7-408f-aad1-6f37645a02f8/terraform-bin apply -auto-approve -no-color
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 0s [id=38cffcc197ca7a52a64ab04ff3c9f73dba3eee77]
aws_dynamodb_table.Register: Refreshing state... [id=feature-send-registration-mail-Register]
data.aws_iam_role.role: Reading...
data.aws_caller_identity.current: Reading...
aws_cloudwatch_event_rule.scheduler: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan]
aws_dynamodb_table.Users: Refreshing state... [id=feature-send-registration-mail-Users]
data.aws_iam_policy_document.override: Reading...
aws_api_gateway_rest_api.api: Refreshing state... [id=c3msk8vrld]
aws_s3_bucket.images: Refreshing state... [id=feature-send-registration-mail-djansang]
aws_dynamodb_table.Link_table: Refreshing state... [id=feature-send-registration-mail-Link_table]
data.aws_iam_policy_document.override: Read complete after 0s [id=2656879482]
aws_s3_bucket.website: Refreshing state... [id=feature-send-registration-mail-mtchoun-mouh.mongulu.cm]
data.aws_caller_identity.current: Read complete after 0s [id=053932140667]
data.aws_iam_role.role: Read complete after 0s [id=website-deployer]
aws_lambda_function.scan: Refreshing state... [id=feature-send-registration-mail-scan_user_consulcam]
aws_lambda_function.lambda: Refreshing state... [id=feature-send-registration-mail-user_registration_consulcam]
aws_api_gateway_resource.resource: Refreshing state... [id=nr7et2]
aws_api_gateway_method.method: Refreshing state... [id=agm-c3msk8vrld-nr7et2-POST]
module.cors.aws_api_gateway_method._: Refreshing state... [id=agm-c3msk8vrld-nr7et2-OPTIONS]
aws_cloudwatch_event_target.target: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan-lambda]
aws_lambda_permission.allow_cloudwatch_to_call_check_foo: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_api_gateway_integration.integration: Refreshing state... [id=agi-c3msk8vrld-nr7et2-POST]
aws_api_gateway_method_response.method_response_200: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-POST-200]
aws_lambda_permission.apigw_lambda: Refreshing state... [id=AllowExecutionFromAPIGateway]
module.cors.aws_api_gateway_integration._: Refreshing state... [id=agi-c3msk8vrld-nr7et2-OPTIONS]
module.cors.aws_api_gateway_method_response._: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-OPTIONS-200]
aws_api_gateway_deployment.test: Refreshing state... [id=pnx8wn]
module.cors.aws_api_gateway_integration_response._: Refreshing state... [id=agir-c3msk8vrld-nr7et2-OPTIONS-200]
local_file.demo_page: Refreshing state... [id=e3a19d09a1ff44f2e90820909bcc91c45dd6eef0]
local_file.index_page: Refreshing state... [id=d25db991d30eb07e3ad9ab147c19d8c8111115af]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:15:45.000+0000" -> (known after apply)
      ~ source_code_hash               = "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY=" -> "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-26T11:15:42.000+0000" -> (known after apply)
      ~ source_code_hash               = "EA7hpqca+A9X3rc+qmsHGWt0jZo1hokT9j0/IpUsGqY=" -> "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Nam [...]

2023-01-26 11:33 UTC, tsafacjo commented on api/notify.py
> +    )
@billmetangmo  It's ok.

2023-02-04 12:42 UTC, billmetangmo commented on api/notify.py
> +    )
THanks

2023-02-04 12:43 UTC, billmetangmo reviewed
Commentaires pris en compte. Merci:) !

2023-02-04 13:13 UTC, billmetangmo commented
## Plan Result

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091762455)


<pre><code>Plan: 2 to add, 3 to change, 0 to destroy.</code></pre>

* Create
  * local_file.demo_page
  * local_file.index_page
* Update
  * aws_lambda_function.lambda
  * aws_lambda_function.scan
  * aws_s3_bucket.website


<details><summary>Change Result (Click me)</summary>

```hcl

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:26:08.000+0000" -> (known after apply)
      ~ source_code_hash               = "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs=" -> "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-26T11:26:11.000+0000" -> (known after apply)
      ~ source_code_hash               = "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs=" -> "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var URL = "https://c3msk8vrld.execute-api.eu-central-1.amazonaws.com/feature-send-registration-mail-dev/register";
            
                    var name = $("#name-input").val();
                    var data = {
                      name: name,
                    };
            
                    $.ajax({
                      type: "POST",
                      url: URL,
                      dataType: "json",
                      crossDomain: "true",
                      contentType: "application/json; charset=utf-8",
                      data: JSON.stringify(data),
            
                      success: function (response) {
                        // clear form and show a success message
                        $("#errorMessage>p").html(
                          "Nous avons  trouvé l <a href="+response["message"]+">image</a> d'où provient votre choix &#128578;"
            
                        );
                        $("#errorMessage").css("background", "#0f7555");
                        console.log("ok")
                        $("#errorMessage").modal("show");
                        document.getElementById("contact-form").reset();
                        //location.reload();
                      },
                      error: function () {
                        // show an error message
                        $("#errorMessage>p").html(
                          "Le nom rentré n'existe pas. \n Veuillez vérifier l'orthographe. "
                        );
                        $("#errorMessage").modal("show");
                        //location.reload();
                      },
                    });
                  }
                </script>
              </head>
              <body class="text-center">
                <!--https://aws.amazon.com/fr/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/-->
                <form id="contact-form" method="post" class="form-signin">
                  <div class="mb-2">
                    <img alt="Logo cameroun" width="150" src="Armoiries_cameroun.svg" />
                  </div>
                  <h1 class="h5 font-weight-normal highlight">Si vous êtes là c'est que vous voulez une démonstration. Pas de soucis &#128578; </h1>
                  <h2 class="h6 font-weight-normal highlight">Nous vous proposons donc de choisir un nom au hasard dans le [...]

2023-02-04 13:13 UTC, billmetangmo commented
## :white_check_mark: Apply Succeeded

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091762455)



<pre><code>Apply complete! Resources: 2 added, 3 changed, 0 destroyed.</code></pre>

<details><summary>Details (Click me)</summary>

```hcl
[command]/home/runner/work/_temp/63eb93e5-f145-476d-bbac-02beae1cee6f/terraform-bin apply -auto-approve -no-color
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 0s [id=6dd8ae582c507544ee93155ed65ae6854034560b]
aws_dynamodb_table.Link_table: Refreshing state... [id=feature-send-registration-mail-Link_table]
aws_dynamodb_table.Users: Refreshing state... [id=feature-send-registration-mail-Users]
data.aws_caller_identity.current: Reading...
data.aws_iam_policy_document.override: Reading...
aws_s3_bucket.images: Refreshing state... [id=feature-send-registration-mail-djansang]
aws_cloudwatch_event_rule.scheduler: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan]
aws_api_gateway_rest_api.api: Refreshing state... [id=c3msk8vrld]
data.aws_iam_role.role: Reading...
aws_dynamodb_table.Register: Refreshing state... [id=feature-send-registration-mail-Register]
data.aws_iam_policy_document.override: Read complete after 0s [id=2656879482]
aws_s3_bucket.website: Refreshing state... [id=feature-send-registration-mail-mtchoun-mouh.mongulu.cm]
data.aws_caller_identity.current: Read complete after 0s [id=053932140667]
data.aws_iam_role.role: Read complete after 0s [id=website-deployer]
aws_lambda_function.lambda: Refreshing state... [id=feature-send-registration-mail-user_registration_consulcam]
aws_lambda_function.scan: Refreshing state... [id=feature-send-registration-mail-scan_user_consulcam]
aws_api_gateway_resource.resource: Refreshing state... [id=nr7et2]
aws_api_gateway_method.method: Refreshing state... [id=agm-c3msk8vrld-nr7et2-POST]
module.cors.aws_api_gateway_method._: Refreshing state... [id=agm-c3msk8vrld-nr7et2-OPTIONS]
aws_lambda_permission.allow_cloudwatch_to_call_check_foo: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_cloudwatch_event_target.target: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan-lambda]
module.cors.aws_api_gateway_method_response._: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-OPTIONS-200]
module.cors.aws_api_gateway_integration._: Refreshing state... [id=agi-c3msk8vrld-nr7et2-OPTIONS]
aws_api_gateway_method_response.method_response_200: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-POST-200]
aws_lambda_permission.apigw_lambda: Refreshing state... [id=AllowExecutionFromAPIGateway]
aws_api_gateway_integration.integration: Refreshing state... [id=agi-c3msk8vrld-nr7et2-POST]
aws_api_gateway_deployment.test: Refreshing state... [id=pnx8wn]
module.cors.aws_api_gateway_integration_response._: Refreshing state... [id=agir-c3msk8vrld-nr7et2-OPTIONS-200]
local_file.demo_page: Refreshing state... [id=e3a19d09a1ff44f2e90820909bcc91c45dd6eef0]
local_file.index_page: Refreshing state... [id=d25db991d30eb07e3ad9ab147c19d8c8111115af]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-01-26T11:26:08.000+0000" -> (known after apply)
      ~ source_code_hash               = "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs=" -> "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-01-26T11:26:11.000+0000" -> (known after apply)
      ~ source_code_hash               = "JrG5MtYX20eM4otSsIXrL2kV20w+6rd29CyqVT/edMs=" -> "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Nam [...]

2023-02-04 13:14 UTC, billmetangmo approved these changes

2023-02-04 13:18 UTC, billmetangmo commented
## Plan Result

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091780869)


<pre><code>Plan: 2 to add, 3 to change, 0 to destroy.</code></pre>

* Create
  * local_file.demo_page
  * local_file.index_page
* Update
  * aws_lambda_function.lambda
  * aws_lambda_function.scan
  * aws_s3_bucket.website


<details><summary>Change Result (Click me)</summary>

```hcl

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-02-04T13:13:46.000+0000" -> (known after apply)
      ~ source_code_hash               = "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-02-04T13:13:43.000+0000" -> (known after apply)
      ~ source_code_hash               = "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var URL = "https://c3msk8vrld.execute-api.eu-central-1.amazonaws.com/feature-send-registration-mail-dev/register";
            
                    var name = $("#name-input").val();
                    var data = {
                      name: name,
                    };
            
                    $.ajax({
                      type: "POST",
                      url: URL,
                      dataType: "json",
                      crossDomain: "true",
                      contentType: "application/json; charset=utf-8",
                      data: JSON.stringify(data),
            
                      success: function (response) {
                        // clear form and show a success message
                        $("#errorMessage>p").html(
                          "Nous avons  trouvé l <a href="+response["message"]+">image</a> d'où provient votre choix &#128578;"
            
                        );
                        $("#errorMessage").css("background", "#0f7555");
                        console.log("ok")
                        $("#errorMessage").modal("show");
                        document.getElementById("contact-form").reset();
                        //location.reload();
                      },
                      error: function () {
                        // show an error message
                        $("#errorMessage>p").html(
                          "Le nom rentré n'existe pas. \n Veuillez vérifier l'orthographe. "
                        );
                        $("#errorMessage").modal("show");
                        //location.reload();
                      },
                    });
                  }
                </script>
              </head>
              <body class="text-center">
                <!--https://aws.amazon.com/fr/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/-->
                <form id="contact-form" method="post" class="form-signin">
                  <div class="mb-2">
                    <img alt="Logo cameroun" width="150" src="Armoiries_cameroun.svg" />
                  </div>
                  <h1 class="h5 font-weight-normal highlight">Si vous êtes là c'est que vous voulez une démonstration. Pas de soucis &#128578; </h1>
                  <h2 class="h6 font-weight-normal highlight">Nous vous proposons donc de choisir un nom au hasard dans le [...]

2023-02-04 13:18 UTC, billmetangmo commented
## :white_check_mark: Apply Succeeded

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091780869)



<pre><code>Apply complete! Resources: 2 added, 3 changed, 0 destroyed.</code></pre>

<details><summary>Details (Click me)</summary>

```hcl
[command]/home/runner/work/_temp/dbae30ba-6963-4532-b69e-f799db7ed7a9/terraform-bin apply -auto-approve -no-color
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 1s [id=9a023b89613b73f2bf6cbfb4652bfc8b0c1a1c97]
aws_dynamodb_table.Link_table: Refreshing state... [id=feature-send-registration-mail-Link_table]
aws_api_gateway_rest_api.api: Refreshing state... [id=c3msk8vrld]
aws_dynamodb_table.Register: Refreshing state... [id=feature-send-registration-mail-Register]
aws_s3_bucket.images: Refreshing state... [id=feature-send-registration-mail-djansang]
aws_dynamodb_table.Users: Refreshing state... [id=feature-send-registration-mail-Users]
aws_cloudwatch_event_rule.scheduler: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan]
data.aws_iam_role.role: Reading...
data.aws_iam_policy_document.override: Reading...
data.aws_caller_identity.current: Reading...
data.aws_iam_policy_document.override: Read complete after 0s [id=2656879482]
aws_s3_bucket.website: Refreshing state... [id=feature-send-registration-mail-mtchoun-mouh.mongulu.cm]
data.aws_caller_identity.current: Read complete after 0s [id=053932140667]
data.aws_iam_role.role: Read complete after 0s [id=website-deployer]
aws_lambda_function.scan: Refreshing state... [id=feature-send-registration-mail-scan_user_consulcam]
aws_lambda_function.lambda: Refreshing state... [id=feature-send-registration-mail-user_registration_consulcam]
aws_api_gateway_resource.resource: Refreshing state... [id=nr7et2]
module.cors.aws_api_gateway_method._: Refreshing state... [id=agm-c3msk8vrld-nr7et2-OPTIONS]
aws_api_gateway_method.method: Refreshing state... [id=agm-c3msk8vrld-nr7et2-POST]
aws_cloudwatch_event_target.target: Refreshing state... [id=feature-send-registration-mail-trigger_user_scan-lambda]
aws_lambda_permission.allow_cloudwatch_to_call_check_foo: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_lambda_permission.apigw_lambda: Refreshing state... [id=AllowExecutionFromAPIGateway]
aws_api_gateway_method_response.method_response_200: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-POST-200]
aws_api_gateway_integration.integration: Refreshing state... [id=agi-c3msk8vrld-nr7et2-POST]
module.cors.aws_api_gateway_method_response._: Refreshing state... [id=agmr-c3msk8vrld-nr7et2-OPTIONS-200]
module.cors.aws_api_gateway_integration._: Refreshing state... [id=agi-c3msk8vrld-nr7et2-OPTIONS]
aws_api_gateway_deployment.test: Refreshing state... [id=pnx8wn]
module.cors.aws_api_gateway_integration_response._: Refreshing state... [id=agir-c3msk8vrld-nr7et2-OPTIONS-200]
local_file.demo_page: Refreshing state... [id=e3a19d09a1ff44f2e90820909bcc91c45dd6eef0]
local_file.index_page: Refreshing state... [id=d25db991d30eb07e3ad9ab147c19d8c8111115af]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "feature-send-registration-mail-user_registration_consulcam"
      ~ last_modified                  = "2023-02-04T13:13:46.000+0000" -> (known after apply)
      ~ source_code_hash               = "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "feature-send-registration-mail-scan_user_consulcam"
      ~ last_modified                  = "2023-02-04T13:13:43.000+0000" -> (known after apply)
      ~ source_code_hash               = "CHoBgMag+jzDmmgxzu3LC3BQNEKRm9y2K1V7sgF3UaM=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "feature-send-registration-mail-mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "feature-send-registration-mail"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Nam [...]

2023-02-04 13:20 UTC, merged

2023-02-04 13:21 UTC, billmetangmo commented
## Plan Result

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091793424)


<pre><code>Plan: 2 to add, 3 to change, 0 to destroy.</code></pre>

* Create
  * local_file.demo_page
  * local_file.index_page
* Update
  * aws_lambda_function.lambda
  * aws_lambda_function.scan
  * aws_s3_bucket.website


<details><summary>Change Result (Click me)</summary>

```hcl

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "user_registration_consulcam"
      ~ last_modified                  = "2023-01-13T01:38:55.000+0000" -> (known after apply)
      ~ source_code_hash               = "H1Q+93oaXE+V39GNyKkpxruw9KFfkELO0aAYUmxhKHQ=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "scan_user_consulcam"
      ~ last_modified                  = "2023-01-13T01:38:52.000+0000" -> (known after apply)
      ~ source_code_hash               = "H1Q+93oaXE+V39GNyKkpxruw9KFfkELO0aAYUmxhKHQ=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var URL = "https://00b640wf8j.execute-api.eu-central-1.amazonaws.com/dev/register";
            
                    var name = $("#name-input").val();
                    var data = {
                      name: name,
                    };
            
                    $.ajax({
                      type: "POST",
                      url: URL,
                      dataType: "json",
                      crossDomain: "true",
                      contentType: "application/json; charset=utf-8",
                      data: JSON.stringify(data),
            
                      success: function (response) {
                        // clear form and show a success message
                        $("#errorMessage>p").html(
                          "Nous avons  trouvé l <a href="+response["message"]+">image</a> d'où provient votre choix &#128578;"
            
                        );
                        $("#errorMessage").css("background", "#0f7555");
                        console.log("ok")
                        $("#errorMessage").modal("show");
                        document.getElementById("contact-form").reset();
                        //location.reload();
                      },
                      error: function () {
                        // show an error message
                        $("#errorMessage>p").html(
                          "Le nom rentré n'existe pas. \n Veuillez vérifier l'orthographe. "
                        );
                        $("#errorMessage").modal("show");
                        //location.reload();
                      },
                    });
                  }
                </script>
              </head>
              <body class="text-center">
                <!--https://aws.amazon.com/fr/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/-->
                <form id="contact-form" method="post" class="form-signin">
                  <div class="mb-2">
                    <img alt="Logo cameroun" width="150" src="Armoiries_cameroun.svg" />
                  </div>
                  <h1 class="h5 font-weight-normal highlight">Si vous êtes là c'est que vous voulez une démonstration. Pas de soucis &#128578; </h1>
                  <h2 class="h6 font-weight-normal highlight">Nous vous proposons donc de choisir un nom au hasard dans le <b>communiqué du 22/09/2020</b>.
                      Pour cela rien de plus simple: rendez vous juste sur la page du <a href="https://www.consulacam-marseille.fr/index.php?p=consulat-cameroun-p [...]

2023-02-04 13:21 UTC, billmetangmo commented
## :white_check_mark: Apply Succeeded

[CI link](https://github.com/mongulu-cm/mtchoun-mouh/actions/runs/4091793424)



<pre><code>Apply complete! Resources: 2 added, 3 changed, 0 destroyed.</code></pre>

<details><summary>Details (Click me)</summary>

```hcl
[command]/home/runner/work/_temp/4b9a0e16-ad49-46c2-90aa-67c0baa28233/terraform-bin apply -auto-approve -no-color
data.archive_file.lambda_zip: Reading...
data.archive_file.lambda_zip: Read complete after 1s [id=9a023b89613b73f2bf6cbfb4652bfc8b0c1a1c97]
aws_dynamodb_table.Register: Refreshing state... [id=Register]
aws_cloudwatch_event_rule.scheduler: Refreshing state... [id=trigger_user_scan]
data.aws_iam_role.role: Reading...
data.aws_caller_identity.current: Reading...
aws_s3_bucket.images: Refreshing state... [id=djansang]
data.aws_iam_policy_document.override: Reading...
aws_dynamodb_table.Users: Refreshing state... [id=Users]
aws_api_gateway_rest_api.api: Refreshing state... [id=00b640wf8j]
data.aws_iam_policy_document.override: Read complete after 0s [id=24740024]
aws_dynamodb_table.Link_table: Refreshing state... [id=Link_table]
aws_s3_bucket.website: Refreshing state... [id=mtchoun-mouh.mongulu.cm]
data.aws_caller_identity.current: Read complete after 1s [id=053932140667]
data.aws_iam_role.role: Read complete after 1s [id=website-deployer]
aws_lambda_function.lambda: Refreshing state... [id=user_registration_consulcam]
aws_lambda_function.scan: Refreshing state... [id=scan_user_consulcam]
aws_api_gateway_resource.resource: Refreshing state... [id=1ar6mf]
module.cors.aws_api_gateway_method._: Refreshing state... [id=agm-00b640wf8j-1ar6mf-OPTIONS]
aws_api_gateway_method.method: Refreshing state... [id=agm-00b640wf8j-1ar6mf-POST]
aws_lambda_permission.allow_cloudwatch_to_call_check_foo: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_cloudwatch_event_target.target: Refreshing state... [id=trigger_user_scan-lambda]
module.cors.aws_api_gateway_integration._: Refreshing state... [id=agi-00b640wf8j-1ar6mf-OPTIONS]
module.cors.aws_api_gateway_method_response._: Refreshing state... [id=agmr-00b640wf8j-1ar6mf-OPTIONS-200]
aws_api_gateway_method_response.method_response_200: Refreshing state... [id=agmr-00b640wf8j-1ar6mf-POST-200]
aws_api_gateway_integration.integration: Refreshing state... [id=agi-00b640wf8j-1ar6mf-POST]
aws_lambda_permission.apigw_lambda: Refreshing state... [id=AllowExecutionFromAPIGateway]
aws_api_gateway_deployment.test: Refreshing state... [id=m13nk3]
module.cors.aws_api_gateway_integration_response._: Refreshing state... [id=agir-00b640wf8j-1ar6mf-OPTIONS-200]
local_file.demo_page: Refreshing state... [id=a00c5cbff1319cf859f4585fcdbcb8fcf6dd443e]
local_file.index_page: Refreshing state... [id=d95db5ed9bfbf4c307309ee49597efea9b665640]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "user_registration_consulcam"
      ~ last_modified                  = "2023-01-13T01:38:55.000+0000" -> (known after apply)
      ~ source_code_hash               = "H1Q+93oaXE+V39GNyKkpxruw9KFfkELO0aAYUmxhKHQ=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_lambda_function.scan will be updated in-place
  ~ resource "aws_lambda_function" "scan" {
        id                             = "scan_user_consulcam"
      ~ last_modified                  = "2023-01-13T01:38:52.000+0000" -> (known after apply)
      ~ source_code_hash               = "H1Q+93oaXE+V39GNyKkpxruw9KFfkELO0aAYUmxhKHQ=" -> "QChLlUZ2uo3++P4rYi8Q5hRCv+uZjPq0YZNCsmt2pRo="
        tags                           = {
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (17 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # aws_s3_bucket.website will be updated in-place
  ~ resource "aws_s3_bucket" "website" {
        id                          = "mtchoun-mouh.mongulu.cm"
      ~ policy                      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = "*" -> {
                          + "*" = "AWS"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                        = {
            "Name"        = "Website"
            "environment" = "master"
            "project"     = "mtchoun-mouh"
        }
        # (12 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # local_file.demo_page will be created
  + resource "local_file" "demo_page" {
      + content              = <<-EOT
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width,initial-scale=1.0" />
                <meta name="description" content="Recevez une notification dès la sortie de votre passeport sans prise de tête :)"/>
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                  crossorigin="anonymous"
                ></script>
                <script
                  src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
                  integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
                  crossorigin="anonymous"
                ></script>
                <link
                  rel="stylesheet"
                  href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
                  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
                  crossorigin="anonymous"
                />
                <link rel="stylesheet" href="style.css" />
                <title>Mtchoun' mouh</title>
                <!-- jQuery Modal -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
                <link
                  rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css"
                />
                <script type="text/javascript">
                  $(function () {
                    $("#help").popover({
                      trigger: "focus",
                    });
                  });
            
                  // disable onPaste
                  function disablePaste(e) {
                    return false;
                  }
                  // validate data
                  function controlFormData(e) {
                    e.preventDefault();
                    var Namere = /[A-Za-z]{1}[A-Za-z]/;
                    if (!Namere.test($("#name-input").val())) {
                      //alert("Name can not less than 2 char");
                      $("#errorMessage>p").html("Le nom ne peut avoir moins de 2 caractères!");
                      $("#errorMessage").modal("show");
                      return;
                    }
            
                    $("#confirmationModal").modal("show");
                  }
            
                  function submitToAPI(e) {
                    e.preventDefault();
                    var [...]